// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Gnvm5RRKeHYaBRRsKkckHLxEpCCL-sY',
    appId: '1:201039766736:web:4935a8968069599b0eaad5',
    messagingSenderId: '201039766736',
    projectId: 'login-portal-aabe2',
    authDomain: 'login-portal-aabe2.firebaseapp.com',
    storageBucket: 'login-portal-aabe2.firebasestorage.app',
    measurementId: 'G-4CCS52BW1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGW_-ywnUw2q-lpCwsW0PzpKjFSdnT7sE',
    appId: '1:201039766736:android:7d960bf751faf03d0eaad5',
    messagingSenderId: '201039766736',
    projectId: 'login-portal-aabe2',
    storageBucket: 'login-portal-aabe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERzAAvKzPCXWhtL1IIKXP_n24G8bGrwI',
    appId: '1:201039766736:ios:faf6b5722f49d58e0eaad5',
    messagingSenderId: '201039766736',
    projectId: 'login-portal-aabe2',
    storageBucket: 'login-portal-aabe2.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERzAAvKzPCXWhtL1IIKXP_n24G8bGrwI',
    appId: '1:201039766736:ios:faf6b5722f49d58e0eaad5',
    messagingSenderId: '201039766736',
    projectId: 'login-portal-aabe2',
    storageBucket: 'login-portal-aabe2.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Gnvm5RRKeHYaBRRsKkckHLxEpCCL-sY',
    appId: '1:201039766736:web:c49c49e73d26ae6d0eaad5',
    messagingSenderId: '201039766736',
    projectId: 'login-portal-aabe2',
    authDomain: 'login-portal-aabe2.firebaseapp.com',
    storageBucket: 'login-portal-aabe2.firebasestorage.app',
    measurementId: 'G-BEQPGRP1E3',
  );
}
